pipeline:
    operations:
    -   name: keras.ops.cast
        params:
            dtype: float32
    -   name: band_pass_filter
        params:
            passband:
            - 3000000.0
            - 7000000.0
    - demodulate
    - beamform
    - envelope_detect
    -   name: normalize
        params:
            output_range:
            - 0.0
            - 1.0
    - log_compress
parameters:
    xlims:
    - -0.019
    - 0.019
    zlims:
    - 0.01
    - 0.06
    grid_size_x: 381
    grid_size_z: 501
    dynamic_range:
    - -50
    - 0
