parameters:
  t_peak: [3.328e-06] # SUC beamforming timing reference in s (custom track_11_t_peak)
  xlims: [-0.014, 0.014] # 28 mm
  dynamic_range: [-30, 0]

pipeline:
  operations:
    - name: demodulate
    - name: downsample
      params:
        factor: 1
    - name: beamform
      params:
        beamformer: delay_and_sum
        enable_pfield: false
    - name: envelope_detect
    - name: normalize
    - name: log_compress
