pipeline:
    operations:
    -   name: keras.ops.cast
        params:
            dtype: float32
    - demodulate
    -   name: beamform
        params:
            beamformer: minimum_variance
            subarray_size: 32
            diagonal_loading: 0.01
    - envelope_detect
parameters:
    grid_size_x: 200
    grid_size_z: 300
    xlims:
    - -0.01
    - 0.01
    zlims:
    - 0.01
    - 0.04
    apply_lens_correction: true
    dynamic_range:
    - -20
    - 0
