pipeline:
    operations:
    - openpros.custom_ops.myrearrange
    -   name: openpros.custom_ops.logtransform
        params:
            k: 100000.0
            data_min: -0.25
            data_max: 0.45
    -   name: normalize
        params:
            output_range:
            - -1.0
            - 1.0
    -   name: openpros.network_ops.inversionnetinference
        params:
            preset: inversionnet-openpros
    -   name: normalize
        params:
            output_range:
            - 1300.0
            - 3600.0
            input_range:
            - -1.0
            - 1.0
